// <auto-generated />
namespace CIT280_Capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class orderaddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderaddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201704171320547_orderaddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
