// <auto-generated />
namespace CIT280_Capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class again1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(again1));
        
        string IMigrationMetadata.Id
        {
            get { return "201703221255302_again1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
